# Snowflake Streamlit Environment Configuration
# Este archivo define las dependencias necesarias para ejecutar la aplicaci√≥n
# en Streamlit in Snowflake

name: streamlit_rechazos
channels:
  - snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python
  - pandas
  - streamlit
